/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountInfo {
  'maskedAccountNumber' : string,
  'principal' : Principal,
  'balance' : bigint,
}
export interface Contact { 'name' : string, 'contactPrincipal' : Principal }
export interface Request {
  'to' : Principal,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'rejected' : null },
  'requestId' : string,
  'contactName' : [] | [string],
  'from' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface Transaction {
  'to' : Principal,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null },
  'contactName' : [] | [string],
  'transactionType' : { 'sent' : null } |
    { 'requestReceived' : null } |
    { 'received' : null } |
    { 'requestSent' : null },
  'from' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'transactionId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[string, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAccountInfo' : ActorMethod<[], AccountInfo>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[string], [] | [Contact]>,
  'getContactByPrincipal' : ActorMethod<[Principal], [] | [Contact]>,
  'getRequests' : ActorMethod<[], Array<Request>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestMoney' : ActorMethod<
    [Principal, bigint, string, [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMoney' : ActorMethod<
    [Principal, bigint, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];