/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountInfo = IDL.Record({
  'maskedAccountNumber' : IDL.Text,
  'principal' : IDL.Principal,
  'balance' : IDL.Nat,
});
export const Contact = IDL.Record({
  'name' : IDL.Text,
  'contactPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Request = IDL.Record({
  'to' : IDL.Principal,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'requestId' : IDL.Text,
  'contactName' : IDL.Opt(IDL.Text),
  'from' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'to' : IDL.Principal,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'contactName' : IDL.Opt(IDL.Text),
  'transactionType' : IDL.Variant({
    'sent' : IDL.Null,
    'requestReceived' : IDL.Null,
    'received' : IDL.Null,
    'requestSent' : IDL.Null,
  }),
  'from' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAccountInfo' : IDL.Func([], [AccountInfo], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
  'getContactByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Contact)],
      ['query'],
    ),
  'getRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestMoney' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMoney' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountInfo = IDL.Record({
    'maskedAccountNumber' : IDL.Text,
    'principal' : IDL.Principal,
    'balance' : IDL.Nat,
  });
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'contactPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Request = IDL.Record({
    'to' : IDL.Principal,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'requestId' : IDL.Text,
    'contactName' : IDL.Opt(IDL.Text),
    'from' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'to' : IDL.Principal,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'contactName' : IDL.Opt(IDL.Text),
    'transactionType' : IDL.Variant({
      'sent' : IDL.Null,
      'requestReceived' : IDL.Null,
      'received' : IDL.Null,
      'requestSent' : IDL.Null,
    }),
    'from' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAccountInfo' : IDL.Func([], [AccountInfo], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Text], [IDL.Opt(Contact)], ['query']),
    'getContactByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Contact)],
        ['query'],
      ),
    'getRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestMoney' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMoney' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };